declare type SelectOptions = [string, string][];
export declare type ToolbarConfig = {
    undoRedo?: boolean;
    formatBlockOptions?: boolean;
    fontFamilyOptions?: boolean | SelectOptions;
    fontSizeOptions?: boolean;
    biu?: boolean;
    codeBlock?: boolean;
    link?: boolean;
    textColorPicker?: boolean;
    bgColorPicker?: boolean;
    formatTextOptions?: boolean;
    insertOptions?: boolean;
    align?: boolean;
    paragraph?: boolean;
    heading1?: boolean;
    heading2?: boolean;
    heading3?: boolean;
    table?: boolean;
    numberedList?: boolean;
    bulletedList?: boolean;
    checkList?: boolean;
    embedYoutubeVideo?: boolean;
    embedVideo?: boolean;
    embedPdf?: boolean;
    embedOffice?: boolean;
    UploadDocuments?: boolean;
    alignments?: boolean;
    alignLeft?: boolean;
    alignCenter?: boolean;
    alignRight?: boolean;
    alignJustify?: boolean;
    editorshow?: boolean;
    uppercase?: boolean;
    lowercase?: boolean;
    capitalize?: boolean;
    RTL?: boolean;
    LTR?: boolean;
    selectLang?: boolean;
    ai?: boolean;
};
export {};
